//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9157
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tpDictionary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class VoiceSamples {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal VoiceSamples() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tpDictionary.VoiceSamples", typeof(VoiceSamples).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] a {
            get {
                object obj = ResourceManager.GetObject("a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] akesi {
            get {
                object obj = ResourceManager.GetObject("akesi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ala {
            get {
                object obj = ResourceManager.GetObject("ala", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] alasa {
            get {
                object obj = ResourceManager.GetObject("alasa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ale {
            get {
                object obj = ResourceManager.GetObject("ale", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ali {
            get {
                object obj = ResourceManager.GetObject("ali", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] anpa {
            get {
                object obj = ResourceManager.GetObject("anpa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ante {
            get {
                object obj = ResourceManager.GetObject("ante", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] anu {
            get {
                object obj = ResourceManager.GetObject("anu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] awen {
            get {
                object obj = ResourceManager.GetObject("awen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] e {
            get {
                object obj = ResourceManager.GetObject("e", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] en {
            get {
                object obj = ResourceManager.GetObject("en", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] epiku {
            get {
                object obj = ResourceManager.GetObject("epiku", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] esun {
            get {
                object obj = ResourceManager.GetObject("esun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ijo {
            get {
                object obj = ResourceManager.GetObject("ijo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ike {
            get {
                object obj = ResourceManager.GetObject("ike", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ilo {
            get {
                object obj = ResourceManager.GetObject("ilo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] insa {
            get {
                object obj = ResourceManager.GetObject("insa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] jaki {
            get {
                object obj = ResourceManager.GetObject("jaki", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] jan {
            get {
                object obj = ResourceManager.GetObject("jan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] jasima {
            get {
                object obj = ResourceManager.GetObject("jasima", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] jelo {
            get {
                object obj = ResourceManager.GetObject("jelo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] jo {
            get {
                object obj = ResourceManager.GetObject("jo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kala {
            get {
                object obj = ResourceManager.GetObject("kala", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kalama {
            get {
                object obj = ResourceManager.GetObject("kalama", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kama {
            get {
                object obj = ResourceManager.GetObject("kama", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kasi {
            get {
                object obj = ResourceManager.GetObject("kasi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ken {
            get {
                object obj = ResourceManager.GetObject("ken", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kepeken {
            get {
                object obj = ResourceManager.GetObject("kepeken", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kijetesantakalu {
            get {
                object obj = ResourceManager.GetObject("kijetesantakalu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kili {
            get {
                object obj = ResourceManager.GetObject("kili", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kin {
            get {
                object obj = ResourceManager.GetObject("kin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kipisi {
            get {
                object obj = ResourceManager.GetObject("kipisi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kiwen {
            get {
                object obj = ResourceManager.GetObject("kiwen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ko {
            get {
                object obj = ResourceManager.GetObject("ko", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kokosila {
            get {
                object obj = ResourceManager.GetObject("kokosila", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kon {
            get {
                object obj = ResourceManager.GetObject("kon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ku {
            get {
                object obj = ResourceManager.GetObject("ku", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kule {
            get {
                object obj = ResourceManager.GetObject("kule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kulupu {
            get {
                object obj = ResourceManager.GetObject("kulupu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kute {
            get {
                object obj = ResourceManager.GetObject("kute", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] la {
            get {
                object obj = ResourceManager.GetObject("la", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] lanpan {
            get {
                object obj = ResourceManager.GetObject("lanpan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] lape {
            get {
                object obj = ResourceManager.GetObject("lape", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] laso {
            get {
                object obj = ResourceManager.GetObject("laso", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] lawa {
            get {
                object obj = ResourceManager.GetObject("lawa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] leko {
            get {
                object obj = ResourceManager.GetObject("leko", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] len {
            get {
                object obj = ResourceManager.GetObject("len", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] lete {
            get {
                object obj = ResourceManager.GetObject("lete", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] li {
            get {
                object obj = ResourceManager.GetObject("li", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] lili {
            get {
                object obj = ResourceManager.GetObject("lili", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] linja {
            get {
                object obj = ResourceManager.GetObject("linja", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] lipu {
            get {
                object obj = ResourceManager.GetObject("lipu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] loje {
            get {
                object obj = ResourceManager.GetObject("loje", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] lon {
            get {
                object obj = ResourceManager.GetObject("lon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] luka {
            get {
                object obj = ResourceManager.GetObject("luka", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] lukin {
            get {
                object obj = ResourceManager.GetObject("lukin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] lupa {
            get {
                object obj = ResourceManager.GetObject("lupa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ma {
            get {
                object obj = ResourceManager.GetObject("ma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] mama {
            get {
                object obj = ResourceManager.GetObject("mama", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] mani {
            get {
                object obj = ResourceManager.GetObject("mani", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] meli {
            get {
                object obj = ResourceManager.GetObject("meli", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] meso {
            get {
                object obj = ResourceManager.GetObject("meso", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] mi {
            get {
                object obj = ResourceManager.GetObject("mi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] mije {
            get {
                object obj = ResourceManager.GetObject("mije", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] misikeke {
            get {
                object obj = ResourceManager.GetObject("misikeke", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] moku {
            get {
                object obj = ResourceManager.GetObject("moku", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] moli {
            get {
                object obj = ResourceManager.GetObject("moli", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] monsi {
            get {
                object obj = ResourceManager.GetObject("monsi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] monsuta {
            get {
                object obj = ResourceManager.GetObject("monsuta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] mu {
            get {
                object obj = ResourceManager.GetObject("mu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] mun {
            get {
                object obj = ResourceManager.GetObject("mun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] musi {
            get {
                object obj = ResourceManager.GetObject("musi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] mute {
            get {
                object obj = ResourceManager.GetObject("mute", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] n {
            get {
                object obj = ResourceManager.GetObject("n", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] namako {
            get {
                object obj = ResourceManager.GetObject("namako", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] nanpa {
            get {
                object obj = ResourceManager.GetObject("nanpa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] nasa {
            get {
                object obj = ResourceManager.GetObject("nasa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] nasin {
            get {
                object obj = ResourceManager.GetObject("nasin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] nena {
            get {
                object obj = ResourceManager.GetObject("nena", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ni {
            get {
                object obj = ResourceManager.GetObject("ni", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] nimi {
            get {
                object obj = ResourceManager.GetObject("nimi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] noka {
            get {
                object obj = ResourceManager.GetObject("noka", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] o {
            get {
                object obj = ResourceManager.GetObject("o", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] oko {
            get {
                object obj = ResourceManager.GetObject("oko", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] olin {
            get {
                object obj = ResourceManager.GetObject("olin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ona {
            get {
                object obj = ResourceManager.GetObject("ona", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pakala {
            get {
                object obj = ResourceManager.GetObject("pakala", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pali {
            get {
                object obj = ResourceManager.GetObject("pali", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] palisa {
            get {
                object obj = ResourceManager.GetObject("palisa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pan {
            get {
                object obj = ResourceManager.GetObject("pan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pana {
            get {
                object obj = ResourceManager.GetObject("pana", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pi {
            get {
                object obj = ResourceManager.GetObject("pi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pilin {
            get {
                object obj = ResourceManager.GetObject("pilin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pimeja {
            get {
                object obj = ResourceManager.GetObject("pimeja", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pini {
            get {
                object obj = ResourceManager.GetObject("pini", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pipi {
            get {
                object obj = ResourceManager.GetObject("pipi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] poka {
            get {
                object obj = ResourceManager.GetObject("poka", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] poki {
            get {
                object obj = ResourceManager.GetObject("poki", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pona {
            get {
                object obj = ResourceManager.GetObject("pona", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pu {
            get {
                object obj = ResourceManager.GetObject("pu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sama {
            get {
                object obj = ResourceManager.GetObject("sama", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] seli {
            get {
                object obj = ResourceManager.GetObject("seli", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] selo {
            get {
                object obj = ResourceManager.GetObject("selo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] seme {
            get {
                object obj = ResourceManager.GetObject("seme", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sewi {
            get {
                object obj = ResourceManager.GetObject("sewi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sijelo {
            get {
                object obj = ResourceManager.GetObject("sijelo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sike {
            get {
                object obj = ResourceManager.GetObject("sike", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sin {
            get {
                object obj = ResourceManager.GetObject("sin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sina {
            get {
                object obj = ResourceManager.GetObject("sina", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sinpin {
            get {
                object obj = ResourceManager.GetObject("sinpin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sitelen {
            get {
                object obj = ResourceManager.GetObject("sitelen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] soko {
            get {
                object obj = ResourceManager.GetObject("soko", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sona {
            get {
                object obj = ResourceManager.GetObject("sona", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] soweli {
            get {
                object obj = ResourceManager.GetObject("soweli", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] suli {
            get {
                object obj = ResourceManager.GetObject("suli", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] suno {
            get {
                object obj = ResourceManager.GetObject("suno", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] supa {
            get {
                object obj = ResourceManager.GetObject("supa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] suwi {
            get {
                object obj = ResourceManager.GetObject("suwi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] tan {
            get {
                object obj = ResourceManager.GetObject("tan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] taso {
            get {
                object obj = ResourceManager.GetObject("taso", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] tawa {
            get {
                object obj = ResourceManager.GetObject("tawa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] telo {
            get {
                object obj = ResourceManager.GetObject("telo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] tenpo {
            get {
                object obj = ResourceManager.GetObject("tenpo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] toki {
            get {
                object obj = ResourceManager.GetObject("toki", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] tomo {
            get {
                object obj = ResourceManager.GetObject("tomo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] tonsi {
            get {
                object obj = ResourceManager.GetObject("tonsi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] tu {
            get {
                object obj = ResourceManager.GetObject("tu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] unpa {
            get {
                object obj = ResourceManager.GetObject("unpa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] uta {
            get {
                object obj = ResourceManager.GetObject("uta", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] utala {
            get {
                object obj = ResourceManager.GetObject("utala", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] walo {
            get {
                object obj = ResourceManager.GetObject("walo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wan {
            get {
                object obj = ResourceManager.GetObject("wan", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] waso {
            get {
                object obj = ResourceManager.GetObject("waso", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wawa {
            get {
                object obj = ResourceManager.GetObject("wawa", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] weka {
            get {
                object obj = ResourceManager.GetObject("weka", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wile {
            get {
                object obj = ResourceManager.GetObject("wile", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
